apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-tests
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rukevweubio/Freashapp-tracker.git
    targetRevision: main
    path: k6

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
    syncOptions:
      - CreateNamespace=true