apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load
spec:
  template:
    spec:
      containers:
        - name: k6
          image: rukevweubio/my-k6-test:latest
          args: ["run", "stress.js"]
          env:
            - name: BASE_URL
              value: "http://my-app:3000"
      restartPolicy: Never