apiVersion: batch/v1
kind: CronJob
metadata:
  name: k6-stress-test-scheduled
  namespace: dev
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            role: k6-tester
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 10000
            seccompProfile:
              type: RuntimeDefault
          automountServiceAccountToken: false

          containers:
            - name: k6
              image: rukevweubio/my-load-test:v2
              imagePullPolicy: Always
              args: ["run", "stress.js"]
              env:
                - name: BASE_URL
                  value: "http://my-app:3000"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: "500m"
                  memory: "256Mi"
                limits:
                  cpu: "1000m"
                  memory: "512Mi"

          restartPolicy: OnFailure